server:
  port: 9000
  
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update 
  datasource:
    url: jdbc:mysql://localhost/rms_oauh2
    username: rms
    password: rms
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: NON_NULL
  main:
    allow-bean-definition-overriding: true
    
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:8000/oauth/token_key
        